name: Java CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name:  Run tests
        run: ./mvnw clean test

      - name: Build application
        run: ./mvnw package
      - name: Build Docker image
        run: docker build -t cicd-demo:1.0 .