name: cicd-demo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name : Make maven wrapper executable
        run : chmod +x mvnw

      - name: Run test and build
        run: ./mvnw clean package

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/cicd-demo:${{ github.sha }} \
            .

      - name: Push Docker image
        run: |
          docker push \
            ${{ secrets.DOCKER_USERNAME }}/cicd-demo:${{ github.sha }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            IMAGE=${{ secrets.DOCKER_USERNAME }}/cicd-demo:${{ github.sha }}

            echo "================================"
            echo "Deploying image: $IMAGE"
            echo "================================"

            echo "Pulling latest image..."
            docker pull $IMAGE


            echo "================================"
            echo "Preparing Green"
            echo "================================"

            docker stop cicd-demo-green || true
            docker rm cicd-demo-green || true

            echo "Starting Green container..."

            docker run -d \
              --name cicd-demo-green \
              -p 9092:9091 \
              $IMAGE


            echo "================================"
            echo "Checking Green health"
            echo "================================"

            HEALTHY=false

            for i in {1..30}; do

              if curl --fail http://localhost:9092/actuator/health; then
                HEALTHY=true
                echo "Green is healthy!"
                break
              fi

              echo "Green is not ready. Attempt $i/30"
              sleep 2

            done


            if [ "$HEALTHY" != "true" ]; then

              echo "Green deployment failed!"

              docker logs cicd-demo-green

              docker stop cicd-demo-green || true
              docker rm cicd-demo-green || true

              exit 1

            fi


            echo "================================"
            echo "Green is healthy"
            echo "Switching Nginx"
            echo "================================"


            sudo sed -i \
              's/proxy_pass http:\/\/127.0.0.1:9091;/proxy_pass http:\/\/127.0.0.1:9092;/' \
              /etc/nginx/sites-available/default


            echo "Testing Nginx configuration..."

            sudo nginx -t

            if [ $? -ne 0 ]; then

              echo "Nginx configuration failed!"

              exit 1

            fi


            echo "Reloading Nginx..."

            sudo systemctl reload nginx


            echo "================================"
            echo "Verifying production traffic"
            echo "================================"

            if curl --fail http://localhost/api/hello; then

                echo "Production verification successful!"
                echo "Green is now serving production traffic."

            else

                echo "Production verification FAILED!"
                echo "Starting rollback to Blue..."

                sudo sed -i \
                  's/proxy_pass http:\/\/127.0.0.1:9092;/proxy_pass http:\/\/127.0.0.1:9091;/' \
                  /etc/nginx/sites-available/default

                echo "Testing rollback Nginx configuration..."

                sudo nginx -t

                if [ $? -ne 0 ]; then
                    echo "CRITICAL: Rollback Nginx configuration is invalid!"
                    exit 1
                fi

                sudo systemctl reload nginx

                echo "Traffic successfully rolled back to Blue."

                docker stop cicd-demo-green || true
                docker rm cicd-demo-green || true

                exit 1
            fi